M48
; DRILL file {KiCad 9.0.6-9.0.6~ubuntu22.04.1} date 2026-03-21T15:17:33-0700
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-03-21T15:17:33-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.6-9.0.6~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
%
G90
G05
T1
X130.1Y-96.11
X130.1Y-101.89
M30
